spring:
  datasource:
    url: jdbc:postgresql://localhost:5442/flashkart
    username: userservice
    password: userservice

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
  
  data:
    redis:
      host: localhost
      port: 6378

  session:
    store-type: redis
    timeout: 30m
    redis:
      namespace: flashkart:sessions


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

info:
  app:
    name: FlashKart
    description: Production-grade e-commerce platform
    version: 0.0.1

app:
  security:
    jwt:
      # IMPORTANT: at least 32+ chars (256-bit). Better: base64 secret.
      secret: "kP9z$vR2#qW7!bF0@jH5%sD3^gC8&xL1*tN4_"
      issuer: "flashkart"
      access-token-ttl-minutes: 15
    refresh-token:
      ttl-days: 14
      pepper: "FBwbxboeE8aZkxgjK38WpfsOumoQ2Q8N"

server:
  servlet:
    session:
      cookie:
        name: FK_ADMIN_SESSION
        http-only: true
        secure: false   # prod HTTPS me true
        same-site: lax